name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests        

    - name: Run code
      run: |
        cd workbook
        python actions.py

    - name: Commit changes
      run: |
        git config --local user.email "autoaction@autoaction.com"
        git config --local user.name "[bot]auto-workbook"
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "[bot]auto workbook update"
        else
          echo "No changes to commit"
        fi

    - name: Push changes
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        git push https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/DLST316/BaekjoonPractice.git master
